### ISSUE TITLE
component1 for Optional?

### ISSUE THREAD

**Issue by AlecStrong** [gojuno/koptional#19]
Often times in code i do something like:

```
optionalStream()
  .subscribe { fooOptional ->
    val foo = fooOptional.toNullable()
    if (foo != null) ...
    else ...
  }
```

with `operator fun component1() = toNullable()` implemented on `Optional` I could instead do:

```
optionalStream()
  .subscribe { (foo) ->
    if (foo != null) ...
    else ...
  }
```

tiny optimization. Happy to contribute this if it makes sense but since its api changing I figured I'd issue first in case it doesnt make sense

**Comment by artem-zinnatullin** [comment]
Yep, that looks very reasonable!

@ming13, @dmitry-novikov, @nostra13 thoughts?

**Comment by nostra13** [comment]
Actually we can't do it because this `component1` will cause a conflict with component1 from `Some` data class. It just won't compile.

**Comment by nostra13** [comment]
Ah, alright then.
I'm not sure if it's obvious for users to understand something like `val (foo) = optionalObj` instead of `val foo = optionalObj.toNullable()`. But the idea is interesting.

@AlecStrong  BTW, maybe stream split is option for you?
```
optionalStream()
  .filterSome()
  .subscribe { foo ->
    ...
  }

optionalStream()
  .filterNone()
  .subscribe {
      ...
  }
```

**Comment by artem-zinnatullin** [comment]
Well it's destructuring right, destructuring of Optional is getting its value, I think it's good fit into

**Comment by AlecStrong** [comment]
i could stream split, it gets a little messy if i flatmap based off an optional and the number of streams i have starts telescoping. I think with `Some` destructuring to its value it makes sense for `Optional` to do the same

This could also be done as an extension function but then you have to import `component1` and intellij isnt super good at importing component extension functions

**Comment by ming13** [comment]
Seems more like a clever hack (which @artem-zinnatullin loves) than a semantically-obvious feature. Destructuring is about unwrapping types with multiple properties and not about choosing a mutually exclusive variants. That makes me strongly against it. Thanks for the suggestion though!

**Comment by ming13** [comment]
Ah, damn it, I misread it, sorry.

Unwrapping it to a nullable value actually makes sense. Not sure if it stands good in an explicit vs. implicit argument and still looks like a neat hack. But since it is an opt-in feature we are not forcing any ideas on a consumer. Let’s try it out!

**Comment by pakoito** [comment]
The reason why this is causing so much trouble is that you're using a statement to unwrap an optional/nullable. Try using when instead.

```
optionalStream()
  .subscribe { fooOptional ->
    when (fooOptional) {
      is Some -> ..
      is None -> ...
    }
  }
```

Is that too many characters? Then you need a `fold` function in `Optional`.

```
fooOptional.fold({}, { value -> })
```
